"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var router = express_1.default.Router();
// Hello endpoint
router.get('/hello', function (req, res) {
    res.json({ message: 'Hello from ZuZu API!' });
});
// Example endpoints for a RESTful API
// GET all items
router.get('/items', function (req, res) {
    // In a real application, this would fetch data from a database
    var items = [
        { id: 1, name: 'Item 1', description: 'Description for item 1' },
        { id: 2, name: 'Item 2', description: 'Description for item 2' },
        { id: 3, name: 'Item 3', description: 'Description for item 3' },
    ];
    res.json(items);
});
// GET item by ID
router.get('/items/:id', function (req, res) {
    var id = parseInt(req.params.id);
    // In a real application, this would fetch specific data from a database
    var items = [
        { id: 1, name: 'Item 1', description: 'Description for item 1' },
        { id: 2, name: 'Item 2', description: 'Description for item 2' },
        { id: 3, name: 'Item 3', description: 'Description for item 3' },
    ];
    var item = items.find(function (item) { return item.id === id; });
    if (!item) {
        return res.status(404).json({ message: "Item with ID ".concat(id, " not found") });
    }
    res.json(item);
});
// POST create item
router.post('/items', function (req, res) {
    var _a = req.body, name = _a.name, description = _a.description;
    if (!name || !description) {
        return res.status(400).json({ message: 'Name and description are required' });
    }
    // In a real application, this would create an item in the database
    var newItem = {
        id: 4, // This would be generated by the database
        name: name,
        description: description,
    };
    res.status(201).json(newItem);
});
// PUT update item
router.put('/items/:id', function (req, res) {
    var id = parseInt(req.params.id);
    var _a = req.body, name = _a.name, description = _a.description;
    if (!name && !description) {
        return res.status(400).json({ message: 'At least one field (name or description) is required' });
    }
    // In a real application, this would update an item in the database
    // Here we're just returning a mock response
    var updatedItem = {
        id: id,
        name: name || 'Original name',
        description: description || 'Original description',
    };
    res.json(updatedItem);
});
// User endpoints for a more complete API
router.get('/users', function (req, res) {
    // In a real application, this would fetch users from the database
    var users = [
        { id: 1, name: 'John Doe', email: 'john.doe@example.com', role: 'Admin', lastActive: '2025-03-30' },
        { id: 2, name: 'Jane Smith', email: 'jane.smith@example.com', role: 'Editor', lastActive: '2025-03-29' },
        { id: 3, name: 'Mike Johnson', email: 'mike.johnson@example.com', role: 'User', lastActive: '2025-03-28' },
        { id: 4, name: 'Sarah Williams', email: 'sarah.williams@example.com', role: 'User', lastActive: '2025-03-27' },
        { id: 5, name: 'Alex Brown', email: 'alex.brown@example.com', role: 'Editor', lastActive: '2025-03-26' },
    ];
    // Optional filtering by role
    var role = req.query.role;
    if (role) {
        var filteredUsers = users.filter(function (user) { return user.role.toLowerCase() === role.toLowerCase(); });
        return res.json(filteredUsers);
    }
    res.json(users);
});
// DELETE item
router.delete('/items/:id', function (req, res) {
    var id = parseInt(req.params.id);
    // In a real application, this would delete an item from the database
    // Here we're just returning a success message
    res.json({ message: "Item with ID ".concat(id, " deleted successfully") });
});
exports.default = router;
